r:    
  apt:
  - name: "fonts-dejavu"
  - name: "unixodbc"
  - name: "unixodbc-dev"
  - name: "gfortran"
  - name: "gcc"
  conda:
  - name: "r-base"
    version: ">=3.5"
  - name: "r-arrow"
  - name: "r-covr"
  - name: "r-curl"
  - name: "r-data.table"
  - name: "r-devtools"
  - name: "r-docopt"
  - name: "r-drake"
  - name: "r-e1071"
  - name: "r-formatr"
  - name: "r-fst"
  - name: "r-future"
  - name: "r-future.apply"
  - name: "r-gdtools"
  - name: "r-glmnet"
  - name: "r-glue"
  - name: "r-gmp"
  - name: "r-here"
  - name: "r-hms"
  - name: "r-htmltools"
  - name: "r-httr"
  - name: "r-irkernel"
  - name: "r-lintr"
  - name: "r-littler"
  - name: "r-mass"
  - name: "r-mlbench"
  - name: "r-randomforest"
  - name: "r-rcpparmadillo"
  - name: "r-reticulate"
  - name: "r-rgl"
  - name: "r-rio"
  - name: "r-rjava"
  - name: "r-rmarkdown"
  - name: "r-rodbc"
  - name: "r-rpart"
  - name: "r-rsqlite"
  - name: "r-rstan"
  - name: "r-rweka"
  - name: "r-servr"
  - name: "r-shiny"
  - name: "r-sf"
  - name: "r-svglite"
  - name: "r-testthat"
  - name: "r-tidyverse"
  - name: "r-units"
  - name: "r-validate"
  - name: "r-zeallot"
  - name: "r-zoo"
  - name: "texinfo"
  - name: "unixodbc"
  pip:
  - name: "tensorflow-gpu"
    version: "==2.0.0"
  - name: "tensorflow-probability"
    version: "==0.8"
  - name: "keras"
    version: "==2.3.1"
  cran:
  - name: "renv"
  - name: "tensorflow"
  - name: "keras"
  - name: "greta"
python:
  apt:
  - name: "ffmpeg"
  conda:
  - name: "beautifulsoup4"
  - name: "bokeh"
  - name: "cloudpickle"
  - name: "cython"
  - name: "dask"
  - name: "dill"
  - name: "gpytorch"
  - name: "h5py"
  - name: "hdf5"
  - name: "ignite"
  - name: "ipywidgets"
  - name: "matplotlib"
  - name: "numba"
  - name: "numexpr"
  - name: "numpy"
  - name: "pandas"
  - name: "patsy"
  - name: "protobuf"
  - name: "psycopg2"
  - name: "pytorch"
  - name: "rapids"
    version: "=0.10"
  - name: "scikit-image"
  - name: "scikit-learn"
  - name: "scipy"
  - name: "seaborn"
  - name: "sqlalchemy"
  - name: "statsmodels"
  - name: "sympy"
  - name: "vincent"
  - name: "unixodbc"
  - name: "xlrd"
  pip:
  - name: "ax-platform"
  - name: "captum"
  - name: "torch-geometric"
  - name: "skorch"
  - name: "tiny-tokenizer"      # see flairNLP/flair issue #1327 (23/12/2019)
  - name: "fastai"
  - name: "pytorch-lightning"
  - name: "pyro-ppl"
  - name: "flair"
julia:
  pkg:
  - name: "IJulia"
  - name: "DifferentialEquations"
